### ISSUE TITLE
已经启动了但是访问不了是怎么回事i

### ISSUE THREAD

**Issue by DEKVIW** [sysctl-date/uso.link#1]
root@debian:~/data/golang/Toolbox/cmd/web# ./web
[GIN-debug] [WARNING] Creating an Engine instance with the Logger and Recovery middleware already attached.

[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:   export GIN_MODE=release
 - using code:  gin.SetMode(gin.ReleaseMode)

[GIN-debug] Loaded HTML Templates (170): 
        - capital.html
        - confundirjs.html
        - regexcode.html
        - aesencrypt.html
        - formatjava.html
        - ip2long.html
        - rabbitencrypt.html
        - calcforce.html
        - createmeta.html
        - editor.html
        - formatvbs.html
        - gzip.html
        - tuya.html
        - formatperl.html
        - navtiveunicode.html
        - webstatus.html
        - json2yaml.html
        - allencrypt.html
        - calcpower.html
        - formatc.html
        - html2cj.html
        - htmlescapechar.html
        - json2go.html
        - jsonzip.html
        - ascii.html
        - calcdata.html
        - checkkeyword.html
        - dnsedu.html
        - htaccess2nginx.html
        - htpasswd.html
        - escape.html
        - formatcss.html
        - formatfilter.html
        - html2js.html
        - json.html
        - lishishangdejintian.html
        - pinyin.html
        - whois.html
        - base64.html
        - deencrypt.html
        - dnsdx.html
        - ip.html
        - jieri.html
        - tiaoseban.html
        - unicode.html
        - unixtime.html
        - dns.html
        - morse.html
        - regexdso.html
        - md5.html
        - qrcode.html
        - rmbdaxie.html
        - txtreplace.html
        - utf8.html
        - websocket.html
        - bootstrapicon.html
        - formatcs.html
        - htmloutjs.html
        - jsonlrview.html
        - jsonudview.html
        - password.html
        - textflip.html
        - uuid.html
        - chaodai.html
        - currency.html
        - formathtml.html
        - formatxml.html
        - rc4encrypt.html
        - shizhong.html
        - calcangle.html
        - dnslt.html
        - endecodejs.html
        - hexconvert.html
        - json2excel.html
        - chaicp.html
        - checkweixin.html
        - formatcsql.html
        - header.html
        - hexrgb.html
        - urlcode.html
        - areacode.html
        - keyboardcode.html
        - calclength.html
        - dnstt.html
        - formatpy.html
        - refresh.html
        - runjs.html
        - shuiyin.html
        - desencrypt.html
        - htmlmarkdown.html
        - shaencrypt.html
        - alldns.html
        - calcarea.html
        - chameta.html
        - formatcpp.html
        - img2base64.html
        - txtcount.html
        - caiji.html
        - calctime.html
        - dnsusa.html
        - regexsucha.html
        - requestmethod.html
        - sql2java.html
        - htmltable.html
        - huoxingwen.html
        - keyboardtest.html
        - regex.html
        - urlencode.html
        - worldtime.html
        - contenttype.html
        - formatjs.html
        - formatphp.html
        - guid.html
        - html2ubb.html
        - json2java.html
        - nav.html
        - pagecode.html
        - asciicode.html
        - calcpressure.html
        - dnsyd.html
        - favicon.html
        - index.html
        - tesufuhao.html
        - tripledes.html
        - htmlescape.html
        - json2cs.html
        - px2rem.html
        - random.html
        - html2php.html
        - httpheader.html
        - shupai.html
        - 
        - androidkeycode.html
        - browserinfo.html
        - calcheat.html
        - checkurl.html
        - enlower.html
        - formatruby.html
        - html2all.html
        - linuxcmd.html
        - nianlvli.html
        - ports.html
        - calctemperature.html
        - htmlfromcsv.html
        - link.html
        - shortcut.html
        - xpath.html
        - androidmanifest.html
        - barcode.html
        - formatsql.html
        - json2get.html
        - shaoshuminzu.html
        - wenzitexiao.html
        - autoformat.html
        - camelcase.html
        - excel2json.html
        - zipstringtext.html
        - calcthickness.html
        - calculator.html
        - footer.html
        - json2xml.html
        - quanbaojiao.html
        - textdiff.html
        - useragent.html
        - calcspeed.html
        - calcvolume.html
        - jianfan.html
        - quchong.html
        - subnetmask.html
        - urlthunder.html

[GIN-debug] GET    /static/*filepath         --> github.com/gin-gonic/gin.(*RouterGroup).createStaticHandler.func1 (3 handlers)
[GIN-debug] HEAD   /static/*filepath         --> github.com/gin-gonic/gin.(*RouterGroup).createStaticHandler.func1 (3 handlers)
[GIN-debug] GET    /sitemap.xml              --> uso.link/internal/handler.XmlSiteMap (3 handlers)
[GIN-debug] GET    /sitemap.html             --> uso.link/internal/handler.HtmlSiteMap (3 handlers)
[GIN-debug] GET    /sitemap.txt              --> uso.link/internal/handler.TxtSiteMap (3 handlers)
[GIN-debug] GET    /sitemap                  --> uso.link/internal/handler.TxtSiteMap (3 handlers)
[GIN-debug] GET    /                         --> uso.link/internal/route.WebRule.func1 (3 handlers)
[GIN-debug] GET    /:name.html               --> uso.link/internal/handler.RenderPage (3 handlers)
[GIN-debug] [WARNING] You trusted all proxies, this is NOT safe. We recommend you to set a value.
Please check https://pkg.go.dev/github.com/gin-gonic/gin#readme-don-t-trust-all-proxies for details.
[GIN-debug] Listening and serving HTTP on :12345

**Comment by sysctl-date** [comment]
看日志端口是正常启动的 可以在服务器 `curl 127.0.0.1:12345` 试下
